# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: qnotify

on:
  - push
  - pull_request

jobs:
  test-lin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Set Keys
      env: |
        API_TOKEN: ${{ secrets.API_TOKEN }}
        API_USER: ${{ secrets.API_USER }}
        API_TEST: ${{ secrets.API_TEST }}
    - name: Testrun on linux
      run : |
        python python/main.py
  
  test-win:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint python/main.py --exit-zero
      - name: Set Keys
        env: |
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_USER: ${{ secrets.API_USER }}
          API_TEST: ${{ secrets.API_TEST }}
      - name: Testrun on windows
        run: |
          python python/main.py

  test-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Set Keys
      env: |
        API_TOKEN: ${{ secrets.API_TOKEN }}
        API_USER: ${{ secrets.API_USER }}
        API_TEST: ${{ secrets.API_TEST }}
    - name: Testrun on mac
      run : |
        python python/main.py
